# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-02 15:32
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('level_of_support', models.PositiveSmallIntegerField(blank=True, choices=[(None, 'Unknown'), (1, 'Definite Supporter'), (2, 'Possible Supporter'), (3, 'Neutral'), (4, 'Possible Opponent'), (5, 'Definite Opponent')], null=True)),
                ('notes', models.TextField(blank=True)),
                ('interest_area_envir', models.NullBooleanField(verbose_name='Environment/climate change')),
                ('interest_area_trans', models.NullBooleanField(verbose_name='Transit, infrastructure, and traffic calming')),
                ('interest_area_commu', models.NullBooleanField(verbose_name='Community and youth infrastructure (fields, recreation, programming, libraries, community theater, etc.)')),
                ('interest_area_parks', models.NullBooleanField(verbose_name='Open space, parks, urban farming, off-leash areas.')),
                ('interest_area_zonin', models.NullBooleanField(verbose_name='Zoning/housing/development issues')),
                ('interest_area_immig', models.NullBooleanField(verbose_name='Immigration, equity, and poverty relief')),
                ('interest_area_educa', models.NullBooleanField(verbose_name='Education and the schools')),
                ('interest_area_addic', models.NullBooleanField(verbose_name='Addressing addiction and opioid abuse')),
                ('interest_area_affor', models.NullBooleanField(verbose_name='Affordability')),
                ('interest_area_busin', models.NullBooleanField(verbose_name='Business development')),
                ('interest_area_artis', models.NullBooleanField(verbose_name='Support for artists and art in the community')),
                ('interest_area_histo', models.NullBooleanField(verbose_name='Historic preservation')),
                ('interest_area_safet', models.NullBooleanField(verbose_name='Public safety')),
                ('interest_area_quali', models.NullBooleanField(verbose_name='Quality of life issues (rats, trash, airplane noise, etc.)')),
                ('interest_area_senio', models.NullBooleanField(verbose_name='Issues affecting seniors')),
                ('interest_area_smart', models.NullBooleanField(verbose_name='Smart city infrastructure')),
                ('status', models.PositiveSmallIntegerField(choices=[(0, 'Pending'), (1, 'Complete'), (2, 'Relinquished')], default=0)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Resident',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count_elections', models.PositiveSmallIntegerField(default=0)),
                ('is_my_contact', models.BooleanField()),
                ('resident_id_number', models.CharField(db_index=True, max_length=12)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('last_name', models.CharField(blank=True, max_length=255)),
                ('first_name', models.CharField(blank=True, max_length=255)),
                ('date_of_birth', models.DateField(null=True)),
                ('resident_address_house_number', models.CharField(blank=True, max_length=30)),
                ('resident_address_house_number_suffix', models.CharField(blank=True, max_length=30)),
                ('resident_address_street', models.CharField(blank=True, max_length=255)),
                ('resident_address_apartment_number', models.CharField(blank=True, max_length=30)),
                ('resident_address_zip_code', models.CharField(blank=True, max_length=30)),
                ('occupation', models.CharField(blank=True, max_length=255)),
                ('party_affiliation', models.CharField(blank=True, choices=[('D', 'Democrat'), ('U', 'Unaffiliated'), ('R', 'Republican'), ('', 'Unregistred'), ('G', 'Green'), ('O', 'Other')], max_length=2)),
                ('nationality', models.CharField(blank=True, max_length=255)),
                ('gender', models.CharField(blank=True, choices=[('', 'Unknown'), ('F', 'Female'), ('M', 'Male')], max_length=1)),
                ('ward_number', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('precinct_number', models.PositiveSmallIntegerField(null=True)),
                ('voted_2016_09_08', models.BooleanField()),
                ('donor_local_amount', models.PositiveIntegerField(default=0)),
                ('donor_local_progressive_percent', models.PositiveSmallIntegerField(default=0)),
                ('donor_federal_amount', models.PositiveIntegerField(default=0)),
                ('donor_federal_progressive_percent', models.PositiveSmallIntegerField(default=0)),
                ('university_affiliation_1', models.CharField(blank=True, max_length=255)),
                ('university_affiliation_2', models.CharField(blank=True, max_length=255)),
                ('university_affiliation_3', models.CharField(blank=True, max_length=255)),
                ('child_age_1', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('child_age_2', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('child_age_3', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('length_of_time_in_home', models.CharField(blank=True, max_length=255)),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='contactrecord',
            name='resident',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TalkToTen.Resident'),
        ),
        migrations.AddField(
            model_name='contactrecord',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
