# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-12 15:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TalkToTen', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='resident',
            name='dog_names',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='resident',
            name='known_to_have_dog',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='contactrecord',
            name='level_of_support',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(None, 'Unknown'), (1, 'Definite support'), (2, 'Possible support'), (3, 'Undecided'), (4, 'Not really interested'), (5, 'Definitely not interested')], null=True),
        ),
    ]
