# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-18 19:00
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('TalkToTen', '0002_auto_20170112_1008'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('show_in_contact_form', models.BooleanField(default=True)),
                ('date', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='EventInterest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('will_attend', models.BooleanField()),
                ('contact_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TalkToTen.ContactRecord')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TalkToTen.Event')),
            ],
        ),
        migrations.AlterField(
            model_name='resident',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='contactrecord',
            name='event_interests',
            field=models.ManyToManyField(through='TalkToTen.EventInterest', to='TalkToTen.Event'),
        ),
    ]
