# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-04 20:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TalkToTen', '0003_auto_20170118_1400'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventinterest',
            name='contact_record',
        ),
        migrations.RemoveField(
            model_name='eventinterest',
            name='event',
        ),
        migrations.RemoveField(
            model_name='contactrecord',
            name='event_interests',
        ),
        migrations.RemoveField(
            model_name='event',
            name='show_in_contact_form',
        ),
        migrations.AlterField(
            model_name='contactrecord',
            name='interest_area_addic',
            field=models.BooleanField(default=False, verbose_name='Addressing addiction and opioid abuse'),
        ),
        migrations.AlterField(
            model_name='contactrecord',
            name='interest_area_affor',
            field=models.BooleanField(default=False, verbose_name='Affordability'),
        ),
        migrations.AlterField(
            model_name='contactrecord',
            name='interest_area_artis',
            field=models.BooleanField(default=False, verbose_name='Support for artists and art in the community'),
        ),
        migrations.AlterField(
            model_name='contactrecord',
            name='interest_area_busin',
            field=models.BooleanField(default=False, verbose_name='Business development'),
        ),
        migrations.AlterField(
            model_name='contactrecord',
            name='interest_area_commu',
            field=models.BooleanField(default=False, verbose_name='Community and youth infrastructure (fields, recreation, programming, libraries, community theater, etc.)'),
        ),
        migrations.AlterField(
            model_name='contactrecord',
            name='interest_area_educa',
            field=models.BooleanField(default=False, verbose_name='Education and the schools'),
        ),
        migrations.AlterField(
            model_name='contactrecord',
            name='interest_area_envir',
            field=models.BooleanField(default=False, verbose_name='Environment/climate change'),
        ),
        migrations.AlterField(
            model_name='contactrecord',
            name='interest_area_histo',
            field=models.BooleanField(default=False, verbose_name='Historic preservation'),
        ),
        migrations.AlterField(
            model_name='contactrecord',
            name='interest_area_immig',
            field=models.BooleanField(default=False, verbose_name='Immigration, equity, and poverty relief'),
        ),
        migrations.AlterField(
            model_name='contactrecord',
            name='interest_area_parks',
            field=models.BooleanField(default=False, verbose_name='Open space, parks, urban farming, off-leash areas.'),
        ),
        migrations.AlterField(
            model_name='contactrecord',
            name='interest_area_quali',
            field=models.BooleanField(default=False, verbose_name='Quality of life issues (rats, trash, airplane noise, etc.)'),
        ),
        migrations.AlterField(
            model_name='contactrecord',
            name='interest_area_safet',
            field=models.BooleanField(default=False, verbose_name='Public safety'),
        ),
        migrations.AlterField(
            model_name='contactrecord',
            name='interest_area_senio',
            field=models.BooleanField(default=False, verbose_name='Issues affecting seniors'),
        ),
        migrations.AlterField(
            model_name='contactrecord',
            name='interest_area_smart',
            field=models.BooleanField(default=False, verbose_name='Smart city infrastructure'),
        ),
        migrations.AlterField(
            model_name='contactrecord',
            name='interest_area_trans',
            field=models.BooleanField(default=False, verbose_name='Transit, infrastructure, and traffic calming'),
        ),
        migrations.AlterField(
            model_name='contactrecord',
            name='interest_area_zonin',
            field=models.BooleanField(default=False, verbose_name='Zoning/housing/development issues'),
        ),
        migrations.AlterField(
            model_name='contactrecord',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Pending'), (1, 'Complete'), (2, 'Relinquished'), (3, 'Needs address Postcard'), (4, 'Needs Send Postcard')], default=0),
        ),
        migrations.DeleteModel(
            name='EventInterest',
        ),
    ]
