# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-18 17:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TalkToTen', '0004_auto_20170204_1500'),
    ]

    operations = [
        migrations.AddField(
            model_name='resident',
            name='campaign_donation_amount',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='resident',
            name='child_name_1',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='resident',
            name='child_name_2',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='resident',
            name='child_name_3',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='resident',
            name='does_not_want_to_receive_email',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='resident',
            name='needs_followup',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='resident',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='resident',
            name='volunteer_note',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='resident',
            name='voted_recent_municipal',
            field=models.BooleanField(default=False),
        ),
    ]
