# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-18 17:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TalkToTen', '0005_auto_20170218_1222'),
    ]

    operations = [
        migrations.RenameField(
            model_name='resident',
            old_name='voted_2016_09_08',
            new_name='voted_2016_11_08',
        ),
    ]
