# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-19 20:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TalkToTen', '0006_auto_20170218_1237'),
    ]

    operations = [
        migrations.AddField(
            model_name='resident',
            name='contact_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='resident',
            name='contact_type',
            field=models.CharField(blank=True, choices=[('', 'Not contacted'), ('Canvass', 'Canvass'), ('House party', 'House party'), ('Post card', 'Post card'), ('Talk to ten', 'Talk to Ten'), ('Other', 'Other')], max_length=20),
        ),
        migrations.AddField(
            model_name='resident',
            name='level_of_support',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(None, 'Unknown'), (1, 'Definite support'), (2, 'Possible support'), (3, 'Undecided'), (4, 'Not really interested'), (5, 'Definitely not interested')], null=True),
        ),
    ]
