# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-19 20:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    # choices=[(0, 'Pending'), (1, 'Complete'), (2, 'Relinquished'), (3, 'Needs address Postcard'), (4, 'Needs Send Postcard')], default=0),

    def cleanup_statuses(apps, schema_editor):
        COMPLETE = 1
        RELINQUISHED = 2
        NEEDS_ADDRESS_POSTCARD = 3
        NEEDS_SEND_POSTCARD = 4
        ContactRecord = apps.get_model("TalkToTen", "ContactRecord")
        ContactRecord.objects.filter(status=RELINQUISHED).delete()
        ContactRecord.objects.filter(status__in=[NEEDS_ADDRESS_POSTCARD,NEEDS_SEND_POSTCARD]).update(status=COMPLETE)


    dependencies = [
        ('TalkToTen', '0007_auto_20170219_1502'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactrecord',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Pending'), (1, 'Complete')], default=0),
        ),
        migrations.RunPython(cleanup_statuses)
    ]
