# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-05-15 13:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TalkToTen', '0008_auto_20170219_1518'),
    ]

    operations = [
        migrations.AddField(
            model_name='resident',
            name='phone_came_from_van',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='resident',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='resident',
            name='precinct_number',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
