# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-09-08 18:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TalkToTen', '0011_auto_20170906_1135'),
    ]

    operations = [
        migrations.AddField(
            model_name='resident',
            name='yard_sign',
            field=models.CharField(blank=True, choices=[('', 'No'), ('Y', 'Yes'), ('R', 'Requested')], max_length=20),
        ),
    ]
