# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-09-13 18:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('TalkToTen', '0013_auto_20170911_1053'),
    ]

    operations = [
        migrations.CreateModel(
            name='StreetSegment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ward_number', models.PositiveIntegerField()),
                ('street_name', models.CharField(max_length=255)),
                ('house_number_min', models.PositiveIntegerField()),
                ('house_number_max', models.PositiveIntegerField()),
                ('ordering', models.PositiveIntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='resident',
            name='street_segment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='TalkToTen.StreetSegment'),
        ),
    ]
