# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-09-16 15:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TalkToTen', '0014_auto_20170913_1434'),
    ]

    operations = [
        migrations.AddField(
            model_name='resident',
            name='other_residents_at_address',
            field=models.TextField(blank=True),
        ),
    ]
