# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-09-19 13:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TalkToTen', '0015_resident_other_residents_at_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='resident',
            name='canvass_complete',
            field=models.BooleanField(default=False),
        ),
    ]
