# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-10-01 17:53
from __future__ import unicode_literals

from django.db import migrations, models
from django.db.models import F, Max


def migrate_notes(apps, schema_editor):
    Resident = apps.get_model('TalkToTen', 'Resident')
    for res in Resident.objects.exclude(volunteer_note=''):
        res.notes = res.notes + ', ' + res.volunteer_note
        res.volunteer_note = ''
        res.save()

def migrate_donations(apps, schema_editor):
    Resident = apps.get_model('TalkToTen', 'Resident')
    Household = apps.get_model('TalkToTen', 'Household')
    for household in Household.objects.annotate(donation=Max('resident__campaign_donation_amount')).filter(donation__gt=0):
        for resident in household.resident_set.order_by('-campaign_donation_amount')[1:]:
            resident.campaign_donation_amount=0
            resident.save()


class Migration(migrations.Migration):

    dependencies = [
        ('TalkToTen', '0017_auto_20170926_1042'),
    ]

    operations = [
        migrations.RunPython(migrate_notes),
        migrations.RunPython(migrate_donations),
        migrations.RemoveField(
            model_name='resident',
            name='volunteer_note',
        ),
        migrations.RemoveField(
            model_name='resident',
            name='is_my_contact',
        ),
        migrations.CreateModel(
            name='Volunteer',
            fields=[
            ],
            options={
                'proxy': True,
            },
            bases=('TalkToTen.household',),
        ),
        migrations.AddField(
            model_name='resident',
            name='volunteer_option_canvass',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='resident',
            name='volunteer_option_dear_friend',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='resident',
            name='volunteer_option_election_day',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='resident',
            name='volunteer_option_gotv',
            field=models.BooleanField(default=False),
        ),
    ]
