# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-10-02 20:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TalkToTen', '0018_auto_20171001_1353'),
    ]

    operations = [
        migrations.AddField(
            model_name='resident',
            name='volunteer_option_needs_followup',
            field=models.BooleanField(default=False),
        ),
    ]
