# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-11-03 12:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TalkToTen', '0020_auto_20171006_1115'),
    ]

    operations = [
        migrations.AddField(
            model_name='resident',
            name='category_gotv',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='resident',
            name='voted_2017_11_07',
            field=models.BooleanField(default=False),
        ),
    ]
