# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-11-04 22:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TalkToTen', '0022_household_is_a_building'),
    ]

    operations = [
        migrations.AddField(
            model_name='resident',
            name='gotv_canvass_complete',
            field=models.BooleanField(default=False),
        ),
    ]
