# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-11-16 19:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TalkToTen', '0024_resident_category_election_day_gotv'),
    ]

    operations = [
        migrations.AlterField(
            model_name='household',
            name='house_number',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='household',
            name='street',
            field=models.CharField(blank=True, db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='household',
            name='ward_number',
            field=models.PositiveSmallIntegerField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='streetsegment',
            name='ordering',
            field=models.PositiveIntegerField(db_index=True),
        ),
        migrations.AlterIndexTogether(
            name='household',
            index_together=set([('street', 'house_number', 'house_number_suffix')]),
        ),
    ]
