# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-11-30 14:46
from __future__ import unicode_literals

from django.core.exceptions import ObjectDoesNotExist

import TalkToTen.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone

initial_tags = ()

def populate_initial_tags(apps, schema_editor):
    Resident = apps.get_model('TalkToTen', 'Resident')
    ResidentTag = apps.get_model('TalkToTen', 'ResidentTag')
    for resident_id_number, tag in initial_tags:
        try:
            resident = Resident.objects.get(resident_id_number=resident_id_number)
        except ObjectDoesNotExist:
            continue
        ResidentTag.objects.get_or_create(resident=resident, tag=tag)

class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('TalkToTen', '0025_auto_20171116_1401'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyContactRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_date', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('contact_type', models.CharField(blank=True, choices=[('', 'Unknown'), ('Canvass', 'Canvass'), ('House party', 'House party'), ('Post card', 'Post card'), ('Talk to ten', 'Talk to Ten'), ('Other', 'Other')], max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('follow_up_date', models.DateTimeField(blank=True, default=TalkToTen.models.default_follow_up_date, null=True)),
                ('open', models.BooleanField(default=True)),
                ('contacter', models.ForeignKey(blank=True, default=3, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('resident', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TalkToTen.Resident')),
            ],
        ),
        migrations.CreateModel(
            name='ResidentTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(blank=True, max_length=64, null=True)),
                ('resident', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TalkToTen.Resident')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='residenttag',
            unique_together=set([('resident', 'tag')]),
        ),
        migrations.RunPython(populate_initial_tags),
    ]
