# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-12-01 19:37
from __future__ import unicode_literals

from django.db.models import F

import TalkToTen.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import datetime

from TalkToTen.models import ContactRecord as CR
from TalkToTen.models import Resident as R

from TalkToTen.models import ContactTypeChoices as CTC
from django.contrib.auth.models import User

def migrate_contact_records(apps, schema_editor):
    steph_id = User.objects.filter(username='shirsch').values_list('id', flat=True).first() or 1

    ContactRecord = apps.get_model('TalkToTen', 'ContactRecord')
    ContactRecord.objects.all().update(follow_up_date=None, contact_type=CTC.TALK_TO_TEN, open=False, contact_date=F('created'))
    ContactRecord.objects.filter(status=CR.PENDING).update(open=True)

    Resident = apps.get_model('TalkToTen', 'Resident')
    for resident in Resident.objects.exclude(contact_type=""):
        if (resident.contact_type==CTC.TALK_TO_TEN and ContactRecord.objects.filter(resident=resident).exists()):
            continue
        ContactRecord.objects.create(
            resident=resident,
            open=False,
            contacter_id = steph_id,
            follow_up_date=None,
            contact_type=resident.contact_type,
            contact_date=resident.contact_date,
            status=CR.COMPLETE_BUT_UNRESERVED
        )

class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('TalkToTen', '0026_auto_20171130_0946'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mycontactrecord',
            name='contacter',
        ),
        migrations.RemoveField(
            model_name='mycontactrecord',
            name='resident',
        ),
        migrations.RenameField(
            model_name='contactrecord',
            old_name='user',
            new_name='contacter'
        ),
        migrations.AddField(
            model_name='contactrecord',
            name='contact_date',
            field=models.DateField(blank=True, default=datetime.date.today, null=True),
        ),
        migrations.AddField(
            model_name='contactrecord',
            name='contact_type',
            field=models.CharField(blank=True,
                                   choices=[('', 'Unknown'), ('Canvass', 'Canvass'), ('House party', 'House party'),
                                            ('Post card', 'Post card'), ('Phone call', 'Phone call'),
                                            ('Email', 'Email'), ('Event', 'Event'), ('Talk to ten', 'Talk to Ten'),
                                            ('Other', 'Other')], max_length=20),
        ),
        migrations.AddField(
            model_name='contactrecord',
            name='follow_up_date',
            field=models.DateField(blank=True, default=TalkToTen.models.default_follow_up_date, null=True),
        ),
        migrations.AddField(
            model_name='contactrecord',
            name='open',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='resident',
            name='contact_type',
            field=models.CharField(blank=True, choices=[('', 'Unknown'), ('Canvass', 'Canvass'), ('House party', 'House party'), ('Post card', 'Post card'), ('Phone call', 'Phone call'), ('Event', 'Event'), ('Talk to ten', 'Talk to Ten'), ('Other', 'Other')], max_length=20),
        ),
        migrations.DeleteModel(
            name='MyContactRecord',
        ),
        migrations.AlterField(
            model_name='contactrecord',
            name='contacter',
            field=models.ForeignKey(default=TalkToTen.models.get_steph_id, on_delete=django.db.models.deletion.CASCADE,
                                    to=settings.AUTH_USER_MODEL),
        ),
        migrations.RunPython(migrate_contact_records),
        migrations.RemoveField(
            model_name='resident',
            name='contact_date',
        ),
        migrations.RemoveField(
            model_name='resident',
            name='contact_type',
        ),
        migrations.AlterField(
            model_name='contactrecord',
            name='status',
            field=models.PositiveSmallIntegerField(
                choices=[(0, 'Pending'), (1, 'Complete - Close resident to new contacts'),
                         (2, 'Complete - Open resident to new contacts')], default=2),
        ),

    ]
