# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2018-09-24 15:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TalkToTen', '0028_geo_node_and_edge'),
    ]

    operations = [
        migrations.AddField(
            model_name='resident',
            name='voted_2018_09_04',
            field=models.BooleanField(default=False),
        ),
    ]
